// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhQ8sqtWWM0mGi4IHjg8hLjp_8So7jf50',
    appId: '1:1838996923:android:292b4f230a6de1ac87b89e',
    messagingSenderId: '1838996923',
    projectId: 'cardsim-ce7ae',
    storageBucket: 'cardsim-ce7ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa-EpXDmCSUQ5IO4-1ipoTf7Viiu4p2po',
    appId: '1:1838996923:ios:708c88272c03ef3b87b89e',
    messagingSenderId: '1838996923',
    projectId: 'cardsim-ce7ae',
    storageBucket: 'cardsim-ce7ae.firebasestorage.app',
    androidClientId: '1838996923-n6rpgik1ou542518e00vh6bur6153dkg.apps.googleusercontent.com',
    iosClientId: '1838996923-30hq4bjg34ojd9jbopheoljg94o86pbl.apps.googleusercontent.com',
    iosBundleId: 'games.cardsim.net',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx1hixAvR7Zryl3ERD9aUbYd8ZBG0bas4',
    appId: '1:1838996923:web:4a06cdf3d62994ca87b89e',
    messagingSenderId: '1838996923',
    projectId: 'cardsim-ce7ae',
    authDomain: 'cardsim-ce7ae.firebaseapp.com',
    storageBucket: 'cardsim-ce7ae.firebasestorage.app',
    measurementId: 'G-9NC6KKTZNR',
  );

}